### ISSUE TITLE
rpostback-askpass error on Mac doing Git Push from RStudio to Github

### ISSUE THREAD

**Issue by ghost** [ucsb-bren/students#2]
error: unable to read askpass response from 'rpostback-askpass'
fatal: could not read Username for 'https://github.com': Device not configured

**Comment by bbest** [comment]
From @oharac  [Fixing RStudio push error: unable to read askpass response · Issue #402 · OHI-Science/issues](https://github.com/OHI-Science/issues/issues/402) (private)...

Thanks @bbest for helping troubleshoot this problem.
Running Mac OS X Yosemite, R Studio Version 0.98.1102.  When pushing committed changes within RStudio, would return the error 
- `error: unable to read askpass response from 'rpostback-askpass'`
- `fatal: could not read Username for 'https://github.com': Device not configured`
  ![image](https://cloud.githubusercontent.com/assets/10714327/6833110/e38ed666-d2e7-11e4-9a67-e869bcce2ee5.png)
- (this problem documented in issues ohicore#104 and ohi-science/issues #33).

Here's how he fixed it: basically, he updated git.exe to the latest version, 2.2.1, edited the search path to point to the new version, made sure the git credential.helper was configured to be able to access the OS X keychain, and pushed a test commit from terminal to store the username/password in the keychain, where it can be accessed from other apps like RStudio.  Easy peasy!
1. To check your current version of git.exe, at the terminal command line:
   - `$ git --version` should return something like:
   - `git version 2.2.1` (this is what you’d like to see; I had version 1.9.5)
2. To update, go to http://git-scm.com/download/mac, download the latest git for OS X, install it.  
3. In terminal, type  `git --version` and verify that it reports the new version.  If it shows the new version, great!  Skip to step 5.
   - Don't be sad if it doesn't!  If you still see the old version, the installer put the new version into a different directory, which has a lower priority in the search path, so now to update the search path.  The default Apple git seems to install the git.exe into `/usr/bin/` directory, this particular updater seems to install into `/usr/local/git/bin/` directory.  The search path needs to be updated to look for git.exe in the new directory first.
4. To change the search path, open up the paths file in ‘nano’ editor using ‘sudo’:
   - `$ sudo nano /etc/paths`
   - At the top line of the paths file, add the directory for the updated git: `’/usr/local/git/bin’`(without the quotes) so it looks kind of like the top line here:
     ![untitled](https://cloud.githubusercontent.com/assets/10714327/6833341/76e62de6-d2e9-11e4-95f2-087bfcc549c5.png)
   - Then hit control-X to exit, then Y in response to the save prompt.
5. Make sure your git config is up to date, including credential.helper:
   - `$ git config --global -l` should return something like:
   - `user.name="Casey O'Hara"` 
   - `user.email=ohara@nceas.ucsb.edu`
     - see https://github.com/OHI-Science/ohiprep/wiki/Setup#git_identity for help on updating user.name and user.email
   - `credential.helper=osxkeychain`
     - (if you need to configure the credential helper: https://help.github.com/articles/caching-your-github-password-in-git/)
6. Now while you are in Terminal, go ahead and clone a repository to your computer and push a test commit. Once you are prompted for your username / password, your info will get stored in the keychain:
   - Steps (borrowed from these instructions): https://github.com/OHI-Science/ohiprep/wiki/Setup#git_identity
   - Change your working directory: `cd github`
   - Clone into a repository with a URL _for which you have permissions_, e.g: `git clone https://github.com/omalik/zaf.git`
   - Change directory to that repository: `cd zaf`
   - Check status: `git status`
   - Push a test commit to that repository: `touch test.md` -> `git add test.md` -> `git commit -m "testing"` -> `git status` -> `git push`
   - Check status again: `git status`
7. Now that git is updated and your username/password are set, tell RStudio the location of the new git.exe, if necessary.  In RStudio, select Tools > Global Options…, select the Git/SVN, and browse to the new Git executable (`/usr/local/git/bin/git` if you updated your Git version as above).
   ![screen shot 2015-03-25 at 12 01 29 pm](https://cloud.githubusercontent.com/assets/10714327/6834566/2989b6f4-d2f2-11e4-9022-d16ad1a7ad01.png)

Next time you push a commit from RStudio, it should remember the username/password from your test commit in step 6, and you should be good to go.
