### ISSUE TITLE
Rmd error message (file, "rt")

### ISSUE THREAD

**Issue by sgriff** [ucsb-bren/students#32]
Receiving the error message when trying to add chunk with a read.csv command. Not sure how else to fix this other than setwd(), but wouldn't that create a problem for anyone opening the file on another computer?

**Comment by bbest** [comment]
Hi @sgriff,  this has to do with being unable to open the file, so the path to the csv that you provide in the `read.csv()` function needs to work relative to the sgriff.Rmd file. Make sense?
