### ISSUE TITLE
Cannot issue New Pull Request

### ISSUE THREAD

**Issue by sparrow925** [ucsb-bren/students#36]
I can click the initial "Submit New Pull Request" button from the env-info page, but the next step, the green button is faded and I cannot click on it. I don't see an open Pull Request in my name. Not sure what the cause of this is!

Thanks!
Elise

**Comment by bbest** [comment]
Hi @sparrow925,

Thanks for creating an issue!

Perhaps you weren't signed into Github? Please try again visiting https://github.com/ucsb-bren/env-info/compare/gh-pages...sparrow925:gh-pages

Do you now see the non-faded "Create pull request" button like so?

![image](https://cloud.githubusercontent.com/assets/2837257/12426319/f3fc536a-be8d-11e5-88b5-47efd075d3c7.png)

**Comment by jupa1089** [comment]
I was having the same issue -- make sure you submit the Pull Request from your own account (sparrow925/env-info), not the ucsb-bren/env-info page

**Comment by bbest** [comment]
Ah yes, thanks @jupa1089! @jkidson had the same problem and just figured it out too. Yay team!

**Comment by bbest** [comment]
Looks resolved based on https://github.com/ucsb-bren/env-info/pull/38
