### ISSUE TITLE
Install Packages Code Fix

### ISSUE THREAD

**Issue by jkidson** [ucsb-bren/students#70]
It looks like the R chunk to install the packages isn't working. (On the Week 3: Tutorial on Reading and Wrangling Data page: http://ucsb-bren.github.io/env-info/wk03_dplyr/wk03_dplyr.html#install-packages)

I think the final install.packages command just needs quotes around the p, as follows.

``` r
# install packages if not found
for (p in pkgs){
  if (!require(p, character.only=T)){
    install.packages("p")
  }
}
```

**Comment by bbest** [comment]
Not quite, running `install.packages("p")` would install the package called `"p"`, rather than substituting the variable `p` with the value of the string in the list of `pkgs`.

What's your error message?

**Comment by jkidson** [comment]
Guess it was user error, not sure what the hangup for others is. #strugglebus
