### ISSUE TITLE
[<org>/<org>.github.io] Page build failure

### ISSUE THREAD

**Issue by sparrow925** [ucsb-bren/students#75]
The index.html is not showing up at http://pollute.github.io, and we're getting an email that says:
## [pollute/pollute.github.io] Page build failure

From: _GitHub support@github.com_

The page build failed with the following error:

The submodule `pollute` was not properly initialized with a `.gitmodules` file. For more information, see https://help.github.com/articles/page-build-failed-missing-submodule.

**Comment by bbest** [comment]
I don't know how this advanced [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) feature got initialized to create these black appearing phantom folders:

![image](https://cloud.githubusercontent.com/assets/2837257/12571782/879d4f06-c399-11e5-9dc9-c8b682ccbb13.png)

But this is how I deleted them to get the site http://pollute.github.io to show up.

``` bash
git clone https://github.com/pollute/pollute.github.io.git
cd pollute.github.io
rm -rf pollute
rm -rf pollute.github.io
git commit -a -m "removing phantom folders for https://github.com/ucsb-bren/env-info/issues/75"
git push
```
